version: "3"
services:
  zircon_bet_service:
    image: zircon_bet_service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:80
    volumes:
      - .:/var/www/html
      - ./docker/${APP_ENV}/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - zircon_bet_service
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8
    ports:
      - ${DB_FORWARD_PORT-3306}:3306
    volumes:
      - zircon_mysql:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: asdf1234*
      MYSQL_ROOT_PASSWORD: asdf1234*
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    networks:
      - zircon_bet_service
  redis:
    image: redis:latest
    ports:
      - ${REDIS_FORWARD_PORT-6379}:6379
    networks:
      - zircon_bet_service

volumes:
  zircon_mysql:
    external: true
    name: local_mysql

networks:
  zircon_bet_service:
